# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'RNSegmentIOAnalytics' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'RCTNetwork',
    'RCTWebSocket',
  ]
  pod 'Analytics', '~> 3.2'

end
